# SPDX-License-Identifier: AGPL-3.0
# Copyright (c) 2026 Stella Project Contributors
# 本文件以 AGPL-3.0 许可证发布，全文见项目根目录 LICENSE。
"""兼容层的 LLM 子系统。"""

from .agent import (
    AgentContextWrapper,
    AstrAgentContext,
    BaseAgentRunHooks,
    ContextWrapper,
    call_event_hook,
    response_to_chain,
    run_tool_loop,
)
from .entities import (
    LLMResponse,
    ProviderMeta,
    ProviderMetaData,
    ProviderRequest,
    ProviderType,
    RerankResult,
    TokenUsage,
    ToolCallsResult,
)
from .manager import (
    STELLA_PROVIDER_ID,
    ProviderManager,
    get_provider_manager,
    reset_provider_manager,
)
from .message import (
    AssistantMessageSegment,
    ContentPart,
    ImageURLPart,
    Message,
    SystemMessageSegment,
    TextPart,
    ThinkPart,
    ToolCall,
    ToolCallMessageSegment,
    UserMessageSegment,
)
from .provider import (
    AbstractProvider,
    EmbeddingProvider,
    Provider,
    RerankProvider,
    StellaChatProvider,
    STTProvider,
    TTSProvider,
    trim_messages,
)
from .tool import (
    BaseFunctionToolExecutor,
    FuncCall,
    FunctionTool,
    FunctionToolManager,
    FuncTool,
    ToolSchema,
    ToolSet,
    llm_tools,
)

__all__ = [
    "STELLA_PROVIDER_ID",
    "AbstractProvider",
    "AgentContextWrapper",
    "AssistantMessageSegment",
    "AstrAgentContext",
    "BaseAgentRunHooks",
    "BaseFunctionToolExecutor",
    "ContentPart",
    "ContextWrapper",
    "EmbeddingProvider",
    "FuncCall",
    "FuncTool",
    "FunctionTool",
    "FunctionToolManager",
    "ImageURLPart",
    "LLMResponse",
    "Message",
    "Provider",
    "ProviderManager",
    "ProviderMeta",
    "ProviderMetaData",
    "ProviderRequest",
    "ProviderType",
    "RerankProvider",
    "RerankResult",
    "STTProvider",
    "StellaChatProvider",
    "SystemMessageSegment",
    "TTSProvider",
    "TextPart",
    "ThinkPart",
    "TokenUsage",
    "ToolCall",
    "ToolCallMessageSegment",
    "ToolCallsResult",
    "ToolSchema",
    "ToolSet",
    "UserMessageSegment",
    "call_event_hook",
    "get_provider_manager",
    "llm_tools",
    "reset_provider_manager",
    "response_to_chain",
    "run_tool_loop",
    "trim_messages",
]
